name:                graph
version:             0.1.0.0
github:              "lehmacdj/graph"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/graph#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- deepseq
- mtl
- transformers
- haskeline
- parser-combinators
- megaparsec
- aeson
- bytestring
- base64-bytestring
- directory
- filepath
- directory-tree
- SHA
- http-conduit
- conduit
- validation
- unix
- random-shuffle
- xml-conduit
- html-conduit
- text
- conduit
- conduit-extra
- foreign-store
- free
- freer-simple
- classy-prelude
- witherable

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -XGADTs
    - -XFlexibleContexts
    - -XTypeOperators
    - -XDataKinds
    - -XAllowAmbiguousTypes
    - -XScopedTypeVariables
    - -XRankNTypes
    - -XTypeApplications

executables:
  ge:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - graph

tests:
  graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - graph
    - tasty
    - tasty-hunit
