name:                graph
version:             0.1.0.0
github:              "lehmacdj/graph"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/graph#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- base-orphans
- base64
- base64-bytestring
- bytestring
- classy-prelude
- comonad
- conduit
- conduit-extra
- constraints
- containers
- deepseq
- directory
- directory-tree
- exceptions
- filepath
- foreign-store
- free
- generic-data
- generic-lens
- Glob
- haskeline
- hspec
- hspec-expectations
- html-conduit
- http-conduit
- http-types
- inline-c
- inline-c-objc
- ixset-typed
- lens
- lens-regex-pcre
- megaparsec
- mono-traversable
- mtl
- optparse-applicative
- ordered-containers
- parser-combinators
- pcre-light
- polysemy
- polysemy-plugin
- polysemy-readline
- polysemy-zoo
- random
- random-shuffle
- resourcet
- semigroupoids
- SHA
- tasty
- tasty-discover
- tasty-golden
- tasty-hspec
- tasty-hunit
- tasty-quickcheck
- template-haskell
- temporary
- text
- time
- transformers
- typed-process
- unix
- unliftio
- witherable
- wreq
- xdg-basedir
- xml-conduit

default-extensions:
- BangPatterns
- BlockArguments
- CApiFFI
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- ImpredicativeTypes
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoFieldSelectors
- NoImplicitPrelude
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- QuantifiedConstraints
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- StrictData
- TemplateHaskellQuotes
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

ghc-options:
- -Wall
- -fplugin=Polysemy.Plugin
- -flate-specialise
- -fspecialise-aggressively

cpp-options:
- -DDEBUG

library:
  source-dirs: src
  when:
    - condition: os(darwin)
      then:
        extra-libraries: [ objc ]
        frameworks: [ Foundation ]
        # this makes inline-c work in GHCi
        ghc-options: -fobject-code
      else:
        extra-libraries: []
        frameworks: []

executables:
  ge:
    main:                Main.hs
    source-dirs:         app/ge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

  dump-graph:
    main:                Main.hs
    source-dirs:         app/dump-graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

  scratch:
    main:                Main.hs
    source-dirs:         app/scratch
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

tests:
  graph-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O0 # compile faster, equivalent to --fast
    dependencies:
    - graph
