name:                graph
version:             0.1.0.0
github:              "lehmacdj/graph"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/graph#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64
- base64-bytestring
- bytestring
- classy-prelude
- conduit
- conduit
- conduit-extra
- containers
- deepseq
- directory
- directory-tree
- exceptions
- filepath
- foreign-store
- free
- haskeline
- html-conduit
- http-conduit
- lens
- megaparsec
- mono-traversable
- mtl
- parser-combinators
- optparse-applicative
- polysemy
- polysemy-plugin
- polysemy-readline
- polysemy-zoo
- random
- random-shuffle
- SHA
- text
- time
- transformers
- typed-process
- unix
- unliftio
- validation
- witherable-class
- xdg-basedir
- xml-conduit

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- NoImplicitPrelude
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- DeriveGeneric

ghc-options:
- -Wall
- -fplugin=Polysemy.Plugin
- -flate-specialise
- -fspecialise-aggressively

library:
  source-dirs: src

executables:
  ge:
    main:                Main.hs
    source-dirs:         exe/ge
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

  node-rename:
    main:                Main.hs
    source-dirs:         exe/change-nid
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

  dump-graph:
    main:                Main.hs
    source-dirs:         exe/dump-graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph

tests:
  graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - graph
    - Glob
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-golden
